-- Add new notification types for study sessions
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SESSION_INVITE';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SESSION_STARTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SESSION_JOINED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SESSION_ENDED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SESSION_GOAL_COMPLETED';
