-- =====================================================
-- AI Partner Image Columns Migration
-- Adds image upload and generation support to AIPartnerMessage
-- =====================================================

-- =====================================================
-- STEP 1: ADD IMAGE ENUM VALUE TO AIMessageType
-- =====================================================

-- Check if IMAGE value exists before adding to avoid error
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_enum
        WHERE enumlabel = 'IMAGE'
        AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'AIMessageType')
    ) THEN
        ALTER TYPE "AIMessageType" ADD VALUE 'IMAGE';
    END IF;
END $$;

-- =====================================================
-- STEP 2: ADD IMAGE COLUMNS TO AIPartnerMessage
-- Using IF NOT EXISTS pattern to prevent errors on re-run
-- =====================================================

-- imageUrl: URL of the image (uploaded to storage or generated by DALL-E)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'AIPartnerMessage'
        AND column_name = 'imageUrl'
    ) THEN
        ALTER TABLE "AIPartnerMessage" ADD COLUMN "imageUrl" TEXT;
    END IF;
END $$;

-- imageBase64: Base64 encoded image data for uploaded images (optional storage)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'AIPartnerMessage'
        AND column_name = 'imageBase64'
    ) THEN
        ALTER TABLE "AIPartnerMessage" ADD COLUMN "imageBase64" TEXT;
    END IF;
END $$;

-- imageMimeType: MIME type of the image (e.g., 'image/png', 'image/jpeg')
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'AIPartnerMessage'
        AND column_name = 'imageMimeType'
    ) THEN
        ALTER TABLE "AIPartnerMessage" ADD COLUMN "imageMimeType" TEXT;
    END IF;
END $$;

-- imageType: Type of image - 'uploaded' or 'generated'
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'AIPartnerMessage'
        AND column_name = 'imageType'
    ) THEN
        ALTER TABLE "AIPartnerMessage" ADD COLUMN "imageType" TEXT;
    END IF;
END $$;

-- imagePrompt: For generated images - the prompt used to create the image
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'AIPartnerMessage'
        AND column_name = 'imagePrompt'
    ) THEN
        ALTER TABLE "AIPartnerMessage" ADD COLUMN "imagePrompt" TEXT;
    END IF;
END $$;

-- imageAnalysis: JSON analysis result for uploaded images from GPT-4o Vision
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'AIPartnerMessage'
        AND column_name = 'imageAnalysis'
    ) THEN
        ALTER TABLE "AIPartnerMessage" ADD COLUMN "imageAnalysis" JSONB;
    END IF;
END $$;

-- =====================================================
-- STEP 3: ADD PERFORMANCE INDEXES FOR IMAGE COLUMNS
-- =====================================================

-- Index for filtering messages with images (imageUrl is not null means has image)
CREATE INDEX IF NOT EXISTS "AIPartnerMessage_imageUrl_idx"
ON "AIPartnerMessage"("imageUrl")
WHERE "imageUrl" IS NOT NULL;

-- Index for filtering by image type (uploaded vs generated)
CREATE INDEX IF NOT EXISTS "AIPartnerMessage_imageType_idx"
ON "AIPartnerMessage"("imageType")
WHERE "imageType" IS NOT NULL;

-- Composite index for querying images in a session
CREATE INDEX IF NOT EXISTS "AIPartnerMessage_sessionId_imageType_idx"
ON "AIPartnerMessage"("sessionId", "imageType")
WHERE "imageType" IS NOT NULL;

-- =====================================================
-- STEP 4: ADD VALIDATION CONSTRAINTS
-- =====================================================

-- Ensure imageType is either 'uploaded' or 'generated' when set
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'AIPartnerMessage_imageType_check'
        AND table_name = 'AIPartnerMessage'
    ) THEN
        ALTER TABLE "AIPartnerMessage"
        ADD CONSTRAINT "AIPartnerMessage_imageType_check"
        CHECK ("imageType" IS NULL OR "imageType" IN ('uploaded', 'generated'));
    END IF;
END $$;

-- Ensure imageMimeType is a valid image MIME type when set
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'AIPartnerMessage_imageMimeType_check'
        AND table_name = 'AIPartnerMessage'
    ) THEN
        ALTER TABLE "AIPartnerMessage"
        ADD CONSTRAINT "AIPartnerMessage_imageMimeType_check"
        CHECK (
            "imageMimeType" IS NULL
            OR "imageMimeType" IN (
                'image/jpeg',
                'image/jpg',
                'image/png',
                'image/gif',
                'image/webp'
            )
        );
    END IF;
END $$;

-- =====================================================
-- STEP 5: ADD COMMENTS FOR DOCUMENTATION
-- =====================================================

COMMENT ON COLUMN "AIPartnerMessage"."imageUrl" IS 'URL of the image - can be storage URL for uploads or DALL-E URL for generated images';
COMMENT ON COLUMN "AIPartnerMessage"."imageBase64" IS 'Base64 encoded image data for uploaded images - optional backup storage';
COMMENT ON COLUMN "AIPartnerMessage"."imageMimeType" IS 'MIME type of the image: image/jpeg, image/png, image/gif, image/webp';
COMMENT ON COLUMN "AIPartnerMessage"."imageType" IS 'Type of image: uploaded (user submitted) or generated (DALL-E created)';
COMMENT ON COLUMN "AIPartnerMessage"."imagePrompt" IS 'For generated images: the prompt used to create the image with DALL-E 3';
COMMENT ON COLUMN "AIPartnerMessage"."imageAnalysis" IS 'JSON object containing GPT-4o Vision analysis of uploaded images';

-- =====================================================
-- VERIFICATION QUERIES (for debugging - optional to run)
-- =====================================================

-- Verify columns exist
-- SELECT column_name, data_type, is_nullable
-- FROM information_schema.columns
-- WHERE table_name = 'AIPartnerMessage'
-- AND column_name LIKE 'image%';

-- Verify indexes exist
-- SELECT indexname, indexdef
-- FROM pg_indexes
-- WHERE tablename = 'AIPartnerMessage'
-- AND indexname LIKE '%image%';

-- Verify constraints exist
-- SELECT constraint_name, check_clause
-- FROM information_schema.check_constraints
-- WHERE constraint_name LIKE '%image%';

-- =====================================================
-- NOTE: RLS policies are already in place for AIPartnerMessage
-- from the original add_ai_partner_tables.sql migration.
-- The existing policies automatically cover the new columns
-- because they operate at the row level, not column level.
-- =====================================================

-- Existing RLS policies that protect image columns:
-- - ai_message_select_policy: Users see messages from their sessions
-- - ai_message_insert_policy: Users can add messages to their sessions
-- - ai_message_update_policy: Users can update their own messages
-- - ai_message_delete_policy: Users can delete their own messages

-- =====================================================
-- MIGRATION COMPLETE
-- =====================================================
